{{- $replicaCount := .Values.replicaCount -}}
{{- $chartName := .Chart.Name -}}
{{- $namespace := .Values.namespace -}}
{{- $podAnnotations := .Values.podAnnotations -}}
{{- $image := printf "%s:%s" .Values.image.repository .Values.image.tag }}
{{- $imagePullPolicy := .Values.image.pullPolicy }}

{{- $index := 0 -}}

{{- range .Values.deployments -}}
{{- $index = add1 $index -}}
{{- $latency := default "0" .latency -}}
{{- $latencyVariation := default "0" .latencyVariation -}}
{{- $indexString := toString $index -}}
{{- $httpCode := default "0" .httpCode -}}

{{- $uniqueDeployName := printf "%s-lat%s-latvar%s-index%s" .name $latency $latencyVariation $indexString }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $uniqueDeployName }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $uniqueDeployName }}
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $uniqueDeployName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $uniqueDeployName }}
      annotations:
      {{- if $podAnnotations }}
        {{ toYaml $podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: "default"
      containers:
        - name: {{ $chartName }}
          image: "{{ $image }}"
          imagePullPolicy: "{{ $imagePullPolicy }}"
          env:
            - name: LATENCY
              value: {{ $latency | quote}}
            - name: LATENCY_VARIATION
              value: {{ $latencyVariation | quote}}
            - name: METRICS
              value: "/metrics/metrics.sample"
            - name: MAX_ROUTINES
              value: {{ .maxRoutines | default "0" | quote}}
            - name: ADDR
              value: ":80"
            - name: HTTP_CODE
              value: {{ $httpCode | quote}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: metricsdir
              mountPath: /metrics
      initContainers:
        - name: installmetrics
          image: roobre/mockexporter:latest
          command: [ "/bin/sh","-c" ]
          args:
            - wget {{ .metrics | default "https://raw.githubusercontent.com/newrelic/nri-prometheus/main/load-test/mockexporter/load_test_big_sample.data" | quote}} -O /metrics/metrics.sample
          volumeMounts:
            - name: metricsdir
              mountPath: "/metrics"
      volumes:
        - name: metricsdir
          emptyDir: {}
{{- end -}}
