name: Nightly build

on:
  schedule:
    - cron: "*/2 * * * *"
  push:
    branches:
      - msanmiquel/add-nightly-builds

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO_VERSION: '1.17'
  INTEGRATION: "prometheus"
  ORIGINAL_REPO_NAME: 'marcsanmi/nri-prometheus'
  REPO_FULL_NAME: ${{ github.event.repository.full_name }}
  TAG: nightly
  TAG_SUFFIX: "-nightly" # In order to avoid nightly updating images

jobs:
  release:
    name: Use goreleaser to release the nightlies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#      - name: Add pre-release tag
#          if: ${{ github.event.release.prerelease }}
#          run: |
#            echo "TAG_SUFFIX=-pre" >> $GITHUB_ENV
      - name: do the release
        # The release target is not being executed inside a container (ci/release) since the target
        # compiles docker images (from goreleaser) and that cannot be done inside a container.
        run: make release
        env:
          GENERATE_PACKAGES: true
  #          UPLOAD_PACKAGES: ${{ github.event.release.prerelease }}
